[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qtomos"
version = "0.1.5"
authors = [
  { name="Marcos Lammers", email="marcos.lammers@lifia.info.unlp.edu.ar" },
  { name="Alejandro Fernandez", email="alejandro.fernandez@lifia.info.unlp.edu.ar" },
]
description = "A SpinQ quantum state tomography data acquisition toolset"
readme = "README.md"
requires-python = "==3.8.*"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "spinqit",
    "python-dotenv",
]

[project.scripts]
acquire = "qtomos.acquire_cli:main"

[tool.setuptools.packages.find]
include = ["qtomos*"]
